## General settings for core workspace
[workspace]
dependencies_update = true             # Run `cargo update` in the release PR.
pr_labels = ["release", "crates.io"]   # PR labels.
changelog_update = false               # Disable the changelog for all packages.
git_tag_enable = false                 # Disable individual tags for all packages.
git_release_enable = false             # Disable individual releases for all packages.
semver_check = false                   # Disable API breaking changes checks with cargo-semver-checks.
pr_name = "chore(main): release core"  # PR title template.
pr_branch_prefix = "core-"             # PR branch prefix.


## Changelog configuration
[changelog]
header = """# Changelog

## [Unreleased]
"""

body = """

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
      {% if commit.breaking %}[**breaking**] {% endif %}\
      {{ commit.message | upper_first }} - \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ remote.link }}/commit/{{ commit.id }}))\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]({{ release_link }})
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}]
    {% endif %}\
{% endif %}\

{% for group, commits in commits
| filter(attribute="merge_commit", value=false)
| unique(attribute="message")
| group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor -%}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}\n
"""

commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->⛰️ Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
    { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^style", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test", group = "<!-- 6 -->🧪 Testing" },
    { message = "^chore\\(release\\):", skip = true },
    { message = "^chore: release", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
    { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
    { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
    { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
]


## Core libraries section
[[package]]
name = "zksync_basic_types"
git_release_enable = true
git_tag_enable = true
git_tag_name = "core-libs-v{{version}}"
git_release_name = "core-libs-v{{version}}"
changelog_update = true
changelog_path = "./core/lib/CHANGELOG.md" # Changelog path for core libs.
changelog_include = [
    "zksync_crypto_primitives", "zksync_vlog",
    "zksync_config", "zksync_utils", "zksync_contracts",
    "zksync_db_connection", "zksync_mini_merkle_tree", "zksync_system_constants",
    "zksync_types", "zksync_object_store", "zksync_vm_interface",
    "zksync_prover_interface", "zksync_l1_contract_interface",
    "zksync_dal", "zksync_eth_signer", "zksync_web3_decl",
    "zksync_eth_client", "zksync_storage", "zksync_merkle_tree",
    "zksync_shared_metrics", "zksync_state", "zksync_block_reverter",
    "zksync_env_config", "zksync_protobuf_config", "zksync_core_leftovers",
    "zksync_test_contracts", "zksync_queued_job_processor",
    "zksync_contract_verifier_lib", "zksync_node_test_utils", "zksync_health_check",
    "zksync_multivm", "zksync_commitment_generator", "zksync_consistency_checker",
    "zksync_node_fee_model", "zksync_eth_sender", "zksync_metadata_calculator",
    "zksync_node_genesis", "zksync_external_price_api", "zksync_base_token_adjuster",
    "zksync_mempool", "zksync_vm_executor", "zksync_state_keeper", "zksync_node_sync",
    "zksync_node_api_server", "zksync_node_consensus", "zksync_node_db_pruner",
    "zksync_circuit_breaker", "zksync_contract_verification_server", "zksync_da_client",
    "zksync_da_clients", "zksync_da_dispatcher", "zksync_eth_watch",
    "zksync_external_proof_integration_api", "zksync_house_keeper", "zksync_logs_bloom_backfill",
    "zksync_node_framework_derive", "zksync_reorg_detector", "zksync_snapshots_applier",
    "zksync_node_storage_init", "zksync_proof_data_handler", "zksync_vm_runner",
    "zksync_node_framework", "zksync_tee_verifier"
]
version_group = "core-libs"

[[package]]
name = "zksync_basic_types"
version_group = "core-libs"

[[package]]
name = "zksync_crypto_primitives"
version_group = "core-libs"

[[package]]
name = "zksync_vlog"
version_group = "core-libs"

[[package]]
name = "zksync_config"
version_group = "core-libs"

[[package]]
name = "zksync_utils"
version_group = "core-libs"

[[package]]
name = "zksync_contracts"
version_group = "core-libs"

[[package]]
name = "zksync_db_connection"
version_group = "core-libs"

[[package]]
name = "zksync_mini_merkle_tree"
version_group = "core-libs"

[[package]]
name = "zksync_system_constants"
version_group = "core-libs"

[[package]]
name = "zksync_types"
version_group = "core-libs"

[[package]]
name = "zksync_object_store"
version_group = "core-libs"

[[package]]
name = "zksync_vm_interface"
version_group = "core-libs"

[[package]]
name = "zksync_prover_interface"
version_group = "core-libs"

[[package]]
name = "zksync_l1_contract_interface"
version_group = "core-libs"

[[package]]
name = "zksync_dal"
version_group = "core-libs"

[[package]]
name = "zksync_eth_signer"
version_group = "core-libs"

[[package]]
name = "zksync_web3_decl"
version_group = "core-libs"

[[package]]
name = "zksync_eth_client"
version_group = "core-libs"

[[package]]
name = "zksync_storage"
version_group = "core-libs"

[[package]]
name = "zksync_merkle_tree"
version_group = "core-libs"

[[package]]
name = "zksync_shared_metrics"
version_group = "core-libs"

[[package]]
name = "zksync_state"
version_group = "core-libs"

[[package]]
name = "zksync_block_reverter"
version_group = "core-libs"

[[package]]
name = "zksync_env_config"
version_group = "core-libs"

[[package]]
name = "zksync_protobuf_config"
version_group = "core-libs"

[[package]]
name = "zksync_core_leftovers"
version_group = "core-libs"

[[package]]
name = "zksync_test_contracts"
version_group = "core-libs"

[[package]]
name = "zksync_queued_job_processor"
version_group = "core-libs"

[[package]]
name = "zksync_contract_verifier_lib"
version_group = "core-libs"

[[package]]
name = "zksync_node_test_utils"
version_group = "core-libs"

[[package]]
name = "zksync_health_check"
version_group = "core-libs"

[[package]]
name = "zksync_multivm"
version_group = "core-libs"

[[package]]
name = "zksync_commitment_generator"
version_group = "core-libs"

[[package]]
name = "zksync_consistency_checker"
version_group = "core-libs"

[[package]]
name = "zksync_node_fee_model"
version_group = "core-libs"

[[package]]
name = "zksync_eth_sender"
version_group = "core-libs"

[[package]]
name = "zksync_metadata_calculator"
version_group = "core-libs"

[[package]]
name = "zksync_node_genesis"
version_group = "core-libs"

[[package]]
name = "zksync_external_price_api"
version_group = "core-libs"

[[package]]
name = "zksync_base_token_adjuster"
version_group = "core-libs"

[[package]]
name = "zksync_mempool"
version_group = "core-libs"

[[package]]
name = "zksync_vm_executor"
version_group = "core-libs"

[[package]]
name = "zksync_state_keeper"
version_group = "core-libs"

[[package]]
name = "zksync_node_sync"
version_group = "core-libs"

[[package]]
name = "zksync_node_api_server"
version_group = "core-libs"

[[package]]
name = "zksync_node_consensus"
version_group = "core-libs"

[[package]]
name = "zksync_node_db_pruner"
version_group = "core-libs"

[[package]]
name = "zksync_circuit_breaker"
version_group = "core-libs"

[[package]]
name = "zksync_contract_verification_server"
version_group = "core-libs"

[[package]]
name = "zksync_da_client"
version_group = "core-libs"

[[package]]
name = "zksync_da_clients"
version_group = "core-libs"

[[package]]
name = "zksync_da_dispatcher"
version_group = "core-libs"

[[package]]
name = "zksync_eth_watch"
version_group = "core-libs"

[[package]]
name = "zksync_external_proof_integration_api"
version_group = "core-libs"

[[package]]
name = "zksync_house_keeper"
version_group = "core-libs"

[[package]]
name = "zksync_logs_bloom_backfill"
version_group = "core-libs"

[[package]]
name = "zksync_node_framework_derive"
version_group = "core-libs"

[[package]]
name = "zksync_reorg_detector"
version_group = "core-libs"

[[package]]
name = "zksync_snapshots_applier"
version_group = "core-libs"

[[package]]
name = "zksync_node_storage_init"
version_group = "core-libs"

[[package]]
name = "zksync_proof_data_handler"
version_group = "core-libs"

[[package]]
name = "zksync_vm_runner"
version_group = "core-libs"

[[package]]
name = "zksync_node_framework"
version_group = "core-libs"

[[package]]
name = "zksync_tee_verifier"
version_group = "core-libs"


## Core binaries section
[[package]]
name = "zksync_external_node"
git_release_enable = true
git_tag_enable = true
git_tag_name = "core-bins-v{{version}}"     # Special tag for core binaries
git_release_name = "core-bins-v{{version}}" # GitHub release name for core binaries
changelog_update = true
changelog_path = "./core/bin/CHANGELOG.md"  # Changelog path for core binaries.
changelog_include = [
    "block_reverter", "zksync_external_node",
    "merkle_tree_consistency_checker", "snapshots_creator",
    "selector_generator", "system-constants-generator",
    "verified_sources_fetcher", "zksync_server",
    "genesis_generator", "zksync_tee_prover"
]
version_group = "core-bins"

[[package]]
name = "zksync_contract_verifier"
version_group = "core-bins"
git_tag_enable = true
git_tag_name = "contract_verifier-v{{version}}" # Special tag for contract verifier

[[package]]
name = "block_reverter"
version_group = "core-bins"

[[package]]
name = "zksync_merkle_tree_consistency_checker"
version_group = "core-bins"

[[package]]
name = "zksync_snapshots_creator"
version_group = "core-bins"

[[package]]
name = "zksync_selector_generator"
version_group = "core-bins"

[[package]]
name = "zksync_system_constants_generator"
version_group = "core-bins"

[[package]]
name = "zksync_verified_sources_fetcher"
version_group = "core-bins"

[[package]]
name = "zksync_server"
version_group = "core-bins"

[[package]]
name = "zksync_genesis_generator"
version_group = "core-bins"

[[package]]
name = "zksync_tee_prover"
version_group = "core-bins"
