name: Release

on:
  push:
    branches:
      - main

jobs:

  release-core:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-plz.yaml@v1
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      manifest_path: 'Cargo.toml'
      config: 'release-plz.toml'
      concurrency-suffix: 'core'

  release-prover:
    if: always()
    needs: release-core
    uses: matter-labs/zksync-ci-common/.github/workflows/release-plz.yaml@v1
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      manifest_path: 'prover/Cargo.toml'
      config: 'prover/release-plz.toml'
      concurrency-suffix: 'prover'

  release-zkstack:
    if: always()
    needs: release-prover
    uses: matter-labs/zksync-ci-common/.github/workflows/release-plz.yaml@v1
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      manifest_path: 'zkstack_cli/Cargo.toml'
      config: 'zkstack_cli/release-plz.toml'
      concurrency-suffix: 'zkstack'
